
-- 1. BẢNG DANH MỤC


CREATE TABLE KHOHANG (
    MaKHO VARCHAR(10) PRIMARY KEY,
    TenKHO NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255)
);

CREATE TABLE CONGTRINH (
    MaCT VARCHAR(10) PRIMARY KEY,
    TenCT NVARCHAR(100) NOT NULL,
    DiaDiem NVARCHAR(255)
);

CREATE TABLE NHANVIEN (
    MaNV VARCHAR(10) PRIMARY KEY,
    TenNV NVARCHAR(100) NOT NULL,
    GioiTinh NVARCHAR(10),
    NamSinh INT,
    DiaChi NVARCHAR(255)
);

CREATE TABLE NHACUNGCAP (
    MaNCC VARCHAR(10) PRIMARY KEY,
    TenNCC NVARCHAR(100) NOT NULL,
    DiaChi NVARCHAR(255),
    Email VARCHAR(100)
);


CREATE TABLE VATTU (
    MaVT VARCHAR(10) PRIMARY KEY,
    TenVT NVARCHAR(100) NOT NULL,
    DonVi NVARCHAR(20),
    LoaiVT NVARCHAR(50),
    
);


-- 2. BẢNG PHỤ (SĐT)


CREATE TABLE SDT_NV (
    MaNV VARCHAR(10),
    SDT VARCHAR(15),
    PRIMARY KEY (MaNV, SDT),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);

CREATE TABLE SDT_NCC (
    MaNCC VARCHAR(10),
    SDT VARCHAR(15),
    PRIMARY KEY (MaNCC, SDT),
    FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC)
);


-- 3. TỒN KHO (QUAN TRỌNG)


CREATE TABLE TONKHO (
    MaKHO VARCHAR(10),
    MaVT VARCHAR(10),
    SoLuong INT DEFAULT 0 CHECK (SoLuong >= 0),
    PRIMARY KEY (MaKHO, MaVT),
    FOREIGN KEY (MaKHO) REFERENCES KHOHANG(MaKHO),
    FOREIGN KEY (MaVT) REFERENCES VATTU(MaVT)
);


-- 4. PHIẾU NHẬP


CREATE TABLE PHIEUNHAP (
    MaPN VARCHAR(10) PRIMARY KEY,
    NgayNhap DATE NOT NULL,
    TongTienNhap DECIMAL(18,2),
    MaNCC VARCHAR(10),
    MaNV VARCHAR(10),
    MaKHO VARCHAR(10),
    FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP(MaNCC),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaKHO) REFERENCES KHOHANG(MaKHO)
);


-- 5. PHIẾU XUẤT


CREATE TABLE PHIEUXUAT (
    MaPX VARCHAR(10) PRIMARY KEY,
    NgayXuat DATE NOT NULL,
    TongTienXuat DECIMAL(18,2),
    MaNV VARCHAR(10),
    MaKHO VARCHAR(10),
    
    MaCT VARCHAR(10),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaKHO) REFERENCES KHOHANG(MaKHO),
   
    FOREIGN KEY (MaCT) REFERENCES CONGTRINH(MaCT)
);


-- 6. CHI TIẾT PHIẾU NHẬP


CREATE TABLE CHITIET_PHIEUNHAP (
    MaPN VARCHAR(10),
    MaVT VARCHAR(10),
    DonGiaNhap DECIMAL(18,2) CHECK (DonGiaNhap >= 0),
    SoLuongNhap INT CHECK (SoLuongNhap > 0),
    ThanhTien DECIMAL(18,2),
    PRIMARY KEY (MaPN, MaVT),
    FOREIGN KEY (MaPN) REFERENCES PHIEUNHAP(MaPN),
    FOREIGN KEY (MaVT) REFERENCES VATTU(MaVT)
);


-- 7. CHI TIẾT PHIẾU XUẤT


CREATE TABLE CHITIET_PHIEUXUAT (
    MaPX VARCHAR(10),
    MaVT VARCHAR(10),
    DonGiaXuat DECIMAL(18,2) CHECK (DonGiaXuat >= 0),
    SoLuongXuat INT CHECK (SoLuongXuat > 0),
    ThanhTien DECIMAL(18,2),
    PRIMARY KEY (MaPX, MaVT),
    FOREIGN KEY (MaPX) REFERENCES PHIEUXUAT(MaPX),
    FOREIGN KEY (MaVT) REFERENCES VATTU(MaVT)
);